// Generated by tools/extract_analyze.mjs from docs/holodeck/index.html.
// The app's own analyze() plus its transitive top-level closure.

const fmtT = t => { t = Math.max(0, Math.floor(t)); const h = Math.floor(t / 3600), m = Math.floor(t / 60) % 60, x = t % 60; return (h ? h + ':' + String(m).padStart(2, '0') : m) + ':' + String(x).padStart(2, '0'); };
const W = s => new Set(s.split(' '));
const STOP = W('the a an and or of to in on for with at by from as is are was were be been being will would should could may might can this that these those it its their his her they them we our you your i not no new every per than then also into over under about after before during each which who whom what when where while there here has have had do does did said says last first next more most some any all other such only just very since until because through across between within without upon a day week daily');
const ART = W('The A An This That These Those Our Their Its His Her');
const TITLES = W('Mayor Chef Dr Mr Mrs Ms Prof Professor Minister Director President Senator Judge Councillor Councilor Officer Captain Nurse Sir Dame Chair Chairman Chairwoman Governor Secretary Representative Commissioner Chief Gov Sen Rep Lieutenant General Admiral Sergeant Detective Inspector Superintendent Principal Coach');
const NOT_NAMES = W('U.S U.K US UK EU EDT EST UTC GMT TEU AM PM OK TV IT Top Watch Listen Share Subscribe Transcript Download Sponsor Message Menu Search Sign Log More Read Skip Close Open Getty Images Stockphoto iStock Courtesy Photo Video Audio Advertisement Related Loading He She It They We You');
const LEAD_WORDS = W('But And Or So Yet On In At For From To By With After Before Since When While If As Then Now Here There Why How What Who Where Also Still Even Only Just Last Next Every Some Many Most Other Such Both Each More Than');
const PLACE_FIRST = W('Port Mount Lake Fort Cape Point Isle Gulf');
const MONTHS = W('Jan Feb Mar Apr Jun Jul Aug Sep Sept Oct Nov Dec January February March April May June July August September October November December Monday Tuesday Wednesday Thursday Friday Saturday Sunday');
const ORG = W('Council Authority Farms Dairy Inc Ltd LLC Company Co Department Division Agency Office Group Board Committee University Hospital School Structural Associates Partners Foundation Institute Ministry Commission Services Corporation Corp Bureau Trust Union Party Press News Times Club Team Clinic Lab Labs Industries Court Caucus Congress Administration Guard Navy Army Engineers Association Society Center Service Police Senate House Assembly Bradstreet Line Lines Marine Shipping Holdings Bank Centre Coalition Alliance Network Ministries Initiative Collaborative Partnership');
const ORG_LOWER = new Set([...ORG].map(w => w.toLowerCase()).concat(['inc.', 'ltd.', 'corp.', 'co.', 'plc', 'gmbh', 'llp', 'lp', 'pa', 'pllc', 'inc', 'corp']));
const PLACE = W('Bridge Avenue Street Road River Park Square City County District Station Corridor Lane Way Valley Hill Harbor Harbour Island Bay Lake Coast Airport Market Centre Plaza Quarter North South East West Point Terminal Channel Tunnel Ocean Sea States Kingdom Chile Maryland Virginia Baltimore Singapore Asia America Europe Africa Dundalk');
let HD_TR = null;
function hdT(stage, kind, msg, data) { const T = HD_TR; if (T) T.ev.push({ t: performance.now() - T.t0, stage, kind, msg, ...(data || {}) }); }
const hdF = doc => !!HD_TR && HD_TR.focus.has(doc);
const HD_ENGM = new WeakMap();
function hdEngineMap(eng) { let m = HD_ENGM.get(eng); if (m) return m; m = new Map(); eng.referents.forEach(r => r.surfaces.forEach(sf => { const k = sf.toLowerCase(); if (!m.has(k)) m.set(k, { surface: sf, routes: r.routes, grain: r.grain }); })); HD_ENGM.set(eng, m); return m; }
function hdEngineMerge(t, ns, eng, hy) {
  if (!eng || !hy) return ns;
  const m = hdEngineMap(eng), have = new Set(ns.map(n => n.name.toLowerCase())), out = ns.slice();
  ns.forEach(n => { const r = m.get(n.name.toLowerCase()); if (r) n.engine = r.routes.join('+'); });
  m.forEach((r, k) => {
    if (have.has(k)) return;
    const words = k.split(/\s+/), desc = r.routes.includes('descriptor'), body = desc ? words.slice(1) : words;
    if (!body.length || body.some(w => MONTHS.has(w[0].toUpperCase() + w.slice(1)))) return;
    if (body.length === 1 && typeof ORG_LOWER !== 'undefined' && ORG_LOWER.has(body[0].replace(/[.,]+$/, ''))) return;
    if (hy.functionOnly(body[0]) || hy.functionOnly(body[body.length - 1])) return;
    if (!desc && body.length === 1 && hy.commonOnly(body[0])) return;
    const re = new RegExp('(?<![\\p{L}\\p{N}])' + k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+') + '(?![\\p{L}\\p{N}])', 'giu'); let x;
    while ((x = re.exec(t))) { const s0 = x.index, e0 = s0 + x[0].length; if (out.some(n => s0 < n.e && n.s < e0)) continue; out.push({ name: r.surface, s: s0, e: e0, engine: r.routes.join('+') + (r.grain ? ' · ' + r.grain : ''), engineAdded: true }); }
  });
  return out.sort((a, b) => a.s - b.s);
}
const hdCut = (t, n) => { t = String(t || '').replace(/\s+/g, ' ').trim(); return t.length > n ? t.slice(0, n - 1) + '…' : t; };
function splitSentences(text, tr) {
  const out = []; const re = /[^\n]+?(?:[.!?]+(?=\s|$)|(?=\n)|$)/g; let m;
  const ABBR = /(?:\b(?:a\.m|p\.m|U\.S|U\.K|Mr|Mrs|Ms|Dr|St|Pte|Ltd|Inc|Co|No|vs|Jr|Sr|Gov|Sen|Rep|Mt|Ft|approx|etc|e\.g|i\.e)|\b[A-Z])\.$/;
  // page furniture: short lines repeated 3+ times (running heads/feet) and bare page numbers
  const lc = new Map(); text.split('\n').forEach(l => { const k = l.trim(); if (k.length >= 4 && k.length <= 120) lc.set(k, (lc.get(k) || 0) + 1); });
  const FURN = k => (lc.get(k) || 0) >= 3 && !/[.!?]$/.test(k) || /^(page\s*)?\d{1,3}(\s*(of|\/)\s*\d{1,3})?$/i.test(k); let skipped = false;
  while ((m = re.exec(text))) {
    const raw = m[0]; const lead = raw.length - raw.replace(/^\s+/, '').length; const tt = raw.trim();
    if (!tt) continue;
    const s = m.index + lead, e = s + tt.length; const prev = out[out.length - 1];
    const whole = /(^|\n)[ \t]*$/.test(text.slice(Math.max(0, s - 40), s)) && /^[ \t]*(\n|$)/.test(text.slice(e, e + 40));
    if (whole && FURN(tt)) { skipped = true; tr && tr('sentences', 'furniture', 'Skipped page furniture “' + hdCut(tt, 60) + '” (' + (/^(page\s*)?\d/i.test(tt) ? 'a page number' : 'repeats ' + lc.get(tt) + ' times with no end punctuation') + ')', { s, e }); continue; }
    const gapOK = /^[ \t]*\n[ \t]*$/.test(text.slice(prev ? prev.e : 0, s)) || (skipped && !!prev); skipped = false;
    if (prev && ABBR.test(prev.t) && !/\n/.test(text.slice(prev.e, s))) { tr && tr('sentences', 'join', 'Kept going past “' + hdCut(prev.t.slice(-14), 16) + '”: an abbreviation, not a sentence end', { s: prev.s, e }); prev.e = e; prev.t = text.slice(prev.s, e); continue; }
    // hard-wrapped line (PDF, minutes, transcripts): join when the previous line is unfinished and there's no blank line between
    if (prev && gapOK && !/[.!?:;"”’)\]]$/.test(prev.t) && (/^[a-z(,;–—-]/.test(tt) || /\b(the|of|to|with|and|or|a|an|for|in|on|by|that|from|at|as|is|are|was|were|be|this|its|their|our)$/i.test(prev.t)) && prev.t.length + tt.length < 900) { tr && tr('sentences', 'join', 'Joined a hard-wrapped line: “' + hdCut(prev.t.slice(-24), 26) + '” continues', { s: prev.s, e }); prev.e = e; prev.t = prev.t + ' ' + tt; continue; }
    out.push({ s, e, t: tt });
  }
  return out.filter(x => x.t.length >= 3);
}
let HD_POS = null;
const HD_NOM = ['NOUN', 'PROPN', 'ADJ', 'NUM', 'X', 'SYM'];
const hdPos = w => { if (!HD_POS || (/^[A-Z]{1,3}$/.test(w))) return null; return HD_POS[String(w).toLowerCase().replace(/['’]s$/, '').replace(/[.,;:!?)"”]+$/, '')] || null; };
let HD_REF = null;
function hdHygiene(docs) {
  if (!HD_POS || typeof HDRegion === 'undefined') return null;
  const kindOf = d => d.kind || d.type || d.medium || 'Source';
  const per = new Map(), kind = new Map(), ws = new Map(), midPairs = new Set(); // midPairs: capitalised word pairs written mid-sentence (name-level evidence)
  const bump = (M, k, cap) => { let e = M.get(k); if (!e) M.set(k, e = [0, 0]); e[1]++; if (cap) e[0]++; };
  docs.forEach(d => { const t = d.text || '', re = /[A-Za-z][A-Za-z'’]*/g, P = new Map(); let K = kind.get(kindOf(d)); if (!K) kind.set(kindOf(d), K = new Map()); let m;
    while ((m = re.exec(t))) { if (!m.index || /[.!?:\n"“(•]\s*$/.test(t.slice(Math.max(0, m.index - 3), m.index))) continue; const w = m[0]; if (/^[A-Z]+$/.test(w) && w.length > 1) continue; // all-caps says nothing about casing
      const k = w.toLowerCase(), cap = w !== k; bump(P, k, cap); bump(K, k, cap); bump(ws, k, cap);
      if (cap) { const nx = t.slice(m.index + w.length).match(/^ +([A-Z][A-Za-z'\u2019]*)/); if (nx) midPairs.add(w + ' ' + nx[1]); } }
    per.set(d.id, P); });
  const kindRes = new Map();
  return { forDoc(d, note) {
    const P = per.get(d.id) || new Map(), K = kind.get(kindOf(d)) || new Map(), mine = new Map(), kn = kindOf(d);
    const hy = { note: note || (() => {}), lastWhy: '',
      nonNominal: w => { const c = hdPos(w); if (!c || Object.keys(c).some(x => HD_NOM.includes(x))) return false; return !(/(ed|en|ing)$/i.test(w) && Object.keys(c).every(x => x === 'VERB' || x === 'AUX')); }, // a participle (Written Standards) modifies; a bare imperative (Provide Guest House) does not
      functionOnly: w => { const c = hdPos(w); return !!c && Object.keys(c).every(x => ['ADP', 'CCONJ', 'SCONJ', 'DET', 'AUX', 'PART', 'PRON'].includes(x)); },
      // dominant reading, not any reading: the treebank gives "of" and "The" stray ADV/PRON counts
      clause: w => { if (/(ing|ed)$/i.test(w)) return false; const c = hdPos(w); if (!c || Object.keys(c).some(x => HD_NOM.includes(x))) return false; const top = Object.entries(c).sort((a, b) => b[1] - a[1])[0][0]; return ['AUX', 'PRON', 'ADV', 'SCONJ', 'PART', 'VERB', 'INTJ'].includes(top); },
      commonOnly: w => { const c = hdPos(w); if (!c) return false; return Object.entries(c).sort((a, b) => b[1] - a[1])[0][0] !== 'PROPN'; },
      namePair: (a, b) => midPairs.has(a + ' ' + b),
      ordinaryOpener: w => { if (/^[A-Z]+$/.test(w)) return false; const k = w.toLowerCase(); let r = mine.get(k);
        if (!r) { const e = P.get(k) || [0, 0], ek = K.get(k) || [0, 0], ew = ws.get(k) || [0, 0], c = HD_POS[k]; const pr = c ? [c.PROPN || 0, Object.values(c).reduce((a, b) => a + b, 0)] : [0, 0]; const rf = (HD_REF && HD_REF.casing.get(k)) || [0, 0];
          const L = [{ name: 'this document', k: e[0], n: e[1] }, { name: kn + ' documents', k: ek[0], n: ek[1] }, { name: 'the workspace', k: ew[0], n: ew[1] }, { name: 'General English (live_priors)', k: rf[0], n: rf[1] }, { name: 'the treebank prior', k: pr[0], n: pr[1] }];
          // the outer walk (kind -> workspace -> prior) is the same for every document of this kind: computed once
          const kk = kn + '|' + k; let outer = kindRes.get(kk); if (!outer) kindRes.set(kk, outer = HDRegion.normalRate(L.slice(1), { key: kk }));
          const inner = e[1] ? HDRegion.normalRate([L[0], L.find((x, i) => i > 0 && x.n > e[1]) || L[0]], { key: d.id + '|' + k }) : null;
          r = inner && inner.hop === 'this document' && inner.walk[0].verdict.startsWith('its own') ? inner : outer; mine.set(k, r); }
        hy.lastWhy = r.rate == null ? 'no region has seen ' + qW(w) + ' mid-sentence' : 'normal for ' + qW(w) + ' is set by ' + r.hop + ', where it is capitalised mid-sentence ' + Math.round(r.rate * 100) + '% of the time';
        return r.rate != null && r.rate < 0.5; } };
    return hy; } };
}
const qW = w => '“' + w + '”';
function findNames(t, hy) {
  const out = [];
  // a hyphen only continues the same capitalized word when what follows it is ALSO capitalized
  // (Winston-Salem, Coca-Cola) -- a lowercase continuation (Atlanta-based) is a modifier, not part of the name
  const WORD = "[A-Z][A-Za-z'\\u2019&.]*(?:-[A-Z][A-Za-z'\\u2019&.]*)*";
  const re = new RegExp(WORD + '(?:\\s+(?:of\\s+|and\\s+|&\\s+)?' + WORD + ')*', 'g'); let m;
  const push = (words, idx, title, m, after) => {
    const oi = words.findIndex((w, i) => i > 0 && i < words.length - 1 && ORG.has(w.replace(/[.,]$/, '')) && (() => { const r = words.slice(i + 1); return r.length >= 1 && r.length <= 3 && r.every(x => /^[A-Z][a-z'\u2019.-]+$/.test(x) && !ORG.has(x) && !PLACE.has(x) && !TITLES.has(x.replace(/\.$/, '')) && !/^(of|and)$/.test(x)); })());
    if (oi > 0) { let j2 = idx; for (let i = 0; i <= oi; i++) j2 = next(j2, words[i]); push(words.slice(0, oi + 1), idx, title, m, ' ' + words[oi + 1]); push(words.slice(oi + 1), j2, null, m, after); return; }
    const ji = words.findIndex((w, i) => i > 0 && i < words.length - 1 && /^(and|&)$/.test(w) && (/^[A-Z]{2,}['\u2019]?s?$/.test(words[i - 1]) || /^[A-Z]{2,}$/.test(words[i + 1])));
    if (ji > 0) { let j2 = idx; for (let i = 0; i <= ji; i++) j2 = next(j2, words[i]); push(words.slice(0, ji), idx, title, m, ' ' + words[ji]); push(words.slice(ji + 1), j2, null, m, after); return; }
    for (;;) { if (!words.length) break; const w0 = words[0]; let why = null;
      if (ART.has(w0) || LEAD_WORDS.has(w0) || /^(of|and|&)$/.test(w0)) why = '';
      else if (hy && words.length > 1) { if (hy.nonNominal(w0)) why = qW(w0) + ' has no noun or name reading'; else if (words.length > 2 && /(^|[;:]\s*)[\s"'(]*$/.test(t.slice(0, idx)) && (() => { const cw = (after.match(/\b[A-Za-z]{4,}\b/g) || []); return cw.filter(x => x === x.toLowerCase()).length > cw.filter(x => x !== x.toLowerCase()).length; })() && !hy.namePair(w0, words[1]) && hy.ordinaryOpener(w0)) why = hy.lastWhy + ', this sentence is prose, not a title line, and ' + qW(w0 + ' ' + words[1]) + ' is never written capitalised mid-sentence'; }
      if (why === null) break; if (why) hy.note('lead', words.join(' '), 'dropped the opening ' + qW(w0) + ': ' + why); idx = next(idx, w0); words.shift(); }
    if (words.some(w => /^(Getty|Stockphoto|iStock|Courtesy|Transcript|Sponsor|Shutterstock|Images)$/.test(w))) return;
    while (words.length && (/^(of|and|&)$/.test(words[words.length - 1]) || (hy && words.length > 1 && hy.functionOnly(words[words.length - 1])))) { const wl = words.pop(); if (hy && !/^(of|and|&)$/.test(wl)) hy.note('tail', words.join(' ') + ' ' + wl, 'dropped the dangling ' + qW(wl) + ': it is only ever a function word'); }
    if (!words.length) return;
    words[words.length - 1] = words[words.length - 1].replace(/[.,]+$/, '').replace(/['\u2019]s?$/, '');
    if (words.length === 1 && /^(I|We|You|They|He|She|It|That|There|What|Let|Don|Won|Can|Isn|Didn|Doesn)['\u2019](ve|m|re|ll|d|s|t)$/i.test(words[0])) return;
    if (!words[words.length - 1]) return;
    if (hy) { const cw = words.find(w => hy.clause(w)); if (cw) { hy.note('drop', words.join(' '), 'not a name: ' + qW(cw) + ' has no noun or name reading, so this is a clause or headline'); return; } }
    const atStart = /(^|[;:]\s*)[\s"'(]*$/.test(t.slice(0, idx));
    if (hy && atStart && /^\s*:/.test(after) && words.every(w => hy.commonOnly(w))) { hy.note('label', words.join(' '), 'not a name: a line-opening run of common words followed by a colon is a form label'); return; }
    const acr = /^[A-Z]{2,}$/.test(words[0]);
    if (atStart && words.length === 1 && !title && !acr) return;
    if (words.every(w => MONTHS.has(w) || NOT_NAMES.has(w) || TITLES.has(w.replace(/\.$/, '')) || /^(Vice|Deputy|Assistant|Acting|Interim|Senior|Chief)$/.test(w))) return;
    if (words[0].length < 2) return;
    // a bare company suffix is never a name on its own ("INC", "LLC", "Corp") -- it only counts inside a longer name
    if (words.length === 1 && ORG_LOWER.has(words[0].replace(/[.,]+$/, '').toLowerCase())) { if (hy) hy.note('drop', words[0], 'not a name: a company suffix standing alone'); return; }
    const name = words.join(' ');
    const am = after.match(/^\s*\(([A-Z]{2,})\)/);
    const saidAfter = /^\s+(said|says|told|reported|wants|argued|added|asked|wrote|stated|announced)\b/.test(after);
    out.push({ name, s: idx, e: idx + name.length, title, alias: am ? am[1] : null, saidAfter, acr: acr && words.length === 1 });
  };
  const next = (idx, w) => { const rest = t.slice(idx + w.length); return idx + w.length + (rest.match(/^\s+/) || [''])[0].length; };
  while ((m = re.exec(t))) {
    const words = m[0].split(/\s+/); const after = t.slice(m.index + m[0].length);
    // split at a title word: "Maryland Governor Wes Moore" -> Maryland | (Governor) Wes Moore
    let ti = words.findIndex(w => TITLES.has(w.replace(/\.$/, '')));
    if (ti >= 0) {
      let idx = m.index; for (let i = 0; i < ti; i++) idx = next(idx, words[i]);
      if (ti > 0) push(words.slice(0, ti), m.index, null, m, ' ' + words[ti]);
      let j = ti + 1; idx = next(idx, words[ti]);
      if (words[j] === 'of' && words[j + 1]) { idx = next(next(idx, words[j]), words[j + 1]); j += 2; while (/^(and|&)$/.test(words[j] || '') && words[j + 1]) { idx = next(next(idx, words[j]), words[j + 1]); j += 2; } }
      push(words.slice(j), idx, words[ti], m, after);
    } else push(words, m.index, null, m, after);
  }
  return out;
}
function nameType(n, info) {
  if (info.person) return 'person';
  const last = n.split(' ').pop();
  const first = n.split(' ')[0];
  if (/(Bank|Line)$/.test(last) && /^(East|West|North|South|Metro)/.test(first)) return 'place';
  if (PLACE_FIRST.has(first)) return 'place';
  if (ORG.has(last)) return 'organisation';
  if (PLACE.has(last)) return 'place';
  if (info.acr) return 'organisation';
  if (info.said) return 'person';
  return 'other';
}
function findFigures(t) {
  const out = []; const re = /(\$|£|€)?(\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?)(\s*(million|billion|thousand|bn|k)\b)?(\s*(%|percent|[A-Za-z]+))?/g; let m;
  while ((m = re.exec(t))) {
    if (m.index > 0 && /[A-Za-z0-9:.]/.test(t[m.index - 1])) continue;
    if (t[m.index + m[2].length + (m[1] || '').length] === ':') continue;
    if (m.index > 0 && /[\[(#^↑]/.test(t[m.index - 1])) continue;
    if (/\.\d{4,}$/.test(m[2])) continue;
    if (/\b(jan(uary)?|feb(ruary)?|mar(ch)?|apr(il)?|may|june?|july?|aug(ust)?|sep(t|tember)?|oct(ober)?|nov(ember)?|dec(ember)?|no|number|page|pp?|vol|chapter|section|route|interstate|pier|gate|level|step|line).?\s*$/i.test(t.slice(Math.max(0, m.index - 12), m.index))) continue;
    const cur = m[1], num = parseFloat(m[2].replace(/,/g, '')), mult = m[4];
    let unit = m[6] || '';
    const isYear = !cur && !mult && /^\d{4}$/.test(m[2]) && num >= 1900 && num <= 2099;
    if (isYear) continue;
    let end = m.index + m[0].length;
    if (unit && (STOP.has(unit.toLowerCase()) || /^[A-Z]/.test(unit))) { end -= (m[5] || '').length; unit = ''; }
    let label = '';
    if (cur) unit = cur === '$' ? 'dollars' : cur === '£' ? 'pounds' : 'euros';
    else if (unit === '%' || unit === 'percent') unit = 'percent';
    else if (!unit) continue;
    else if (/^(am|pm|a|an|the|and|or|of|in|on|at|to|by|for|was|were|is|are|th|st|nd|rd|s|times?|years?|months?|days?|hours?|minutes?|seconds?)$/i.test(unit)) continue;
    else { unit = unit.toLowerCase(); const of = t.slice(end).match(/^\s+of\s+([a-z]+)/); label = of ? unit + ' of ' + of[1] : unit; }
    const val = num * ({ million: 1e6, billion: 1e9, bn: 1e9, thousand: 1e3, k: 1e3 }[mult] || 1);
    if (unit === 's' || unit === 'th' || unit === 'st' || unit === 'nd' || unit === 'rd') continue;
    if (['dollars', 'pounds', 'euros', 'percent'].includes(unit)) { const nx = t.slice(end).match(/^\s+(?:of|in|for)\s+(?:the\s+)?([a-z]{4,})/i); if (nx) label = unit + ' ' + nx[0].trim().toLowerCase(); }
    const key = (label && label !== unit ? label : unit).replace(/s$/, '');
    out.push({ raw: t.slice(m.index, end).trim(), value: val, unit: key, label: label || unit, s: m.index, e: end });
  }
  return out;
}
function findDates(t) {
  const out = []; const tr = /\b\d{1,2}:\d{2}(?::\d{2})?(?:\s*[ap]\.m\.)?/g; let tm;
  while ((tm = tr.exec(t))) out.push({ raw: tm[0].trim(), s: tm.index, e: tm.index + tm[0].trim().length, year: null });
  const re = /\b((?:19|20)\d{2}|January|February|March|April|May|June|July|August|September|October|November|December|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|spring|summer|autumn|winter)\b/g; let m;
  while ((m = re.exec(t))) { if (m[1] === 'May' && /\bmay\b/.test(t.slice(m.index, m.index + 3))) continue; out.push({ raw: m[1], s: m.index, e: m.index + m[1].length, year: /^\d{4}$/.test(m[1]) ? +m[1] : null }); }
  return out;
}
function frameOf(t) {
  const l = t.toLowerCase();
  if (/\b(may|might|could|possibly|perhaps|likely|unclear|appears to|seems)\b/.test(l)) return 'uncertain';
  if (/\b(said|says|told|reported|estimated|according to|wants|claims?|claimed|argued|believes?)\b/.test(l)) return 'attributed';
  if (/\b(will|plans? to|should|expected to|expects?|intends?|proposed?|aims? to|scheduled)\b/.test(l)) return 'plan';
  return 'fact';
}
const VERB_RE = /\b(is|are|was|were|be|been|has|have|had|did|does|do|said|says|say|told|will|would|could|can|may|might|must|should)\b|\b[a-z]{3,}(ed|es|ing)\b/i;
function isJunk(st, fu) {
  const t = clean(st.text); const w = t.match(/[A-Za-z]{2,}/g) || [];
  if (w.length < 5) return true;
  if (fu && fu.set.has(fu.nt(t))) return true;
  if (fu && fu.back.some(([a, b]) => st.s >= a && st.s < b)) return true;
  if (/^[\d\s↑^]*(?:[a-z]\s+)*["“]/.test(t) && /^(\d+\s+)+|^[↑^]/.test(t)) return true;
  if (/^\s*[↑^\d.\s]*(retrieved|archived|accessed|source credits|cite|see also)\b|archived from the original|<iframe|^\s*embed\b|\b(photos? by|getty images|ap photo|reuters\/|illustration by|image credit|courtesy of)\b|\bISBN\b|\bdoi:|\(PDF\)|^\s*↑/i.test(t)) return true;
  if (/^(main articles?|see also|further information|for other uses|this article is about|not to be confused|redirects? here)\b/i.test(t)) return true;
  if (/wikimedia commons|\bcommons has media\b|^(jump to|edit|view history|from wikipedia)/i.test(t)) return true;
  if (/^[A-Z][a-z]+(?: [a-z]+){0,2}\s*[;:]\s/.test(t) && !VERB_RE.test(t.slice(t.search(/[;:]/)))) return true;
  if (/^["“][^"”]{10,}["”]\.?$/.test(t)) return true;
  if (/^[A-Z][a-z]+, [A-Z][a-z]+(; [A-Z][a-z]+, [A-Z][a-z]+)*\s*\(/.test(t) || /^[^a-z]*\b(Washington|New York|London), [A-Z.]+:/.test(t)) return true;
  if (!VERB_RE.test(t) && w.length < 14) return true;
  return false;
}
function analyze(corpus, htmlMap) {
  const docs = corpus.docs.map(d => { const x = { ...d }; x.heads = []; x.blocks = [];
    if (x.title && /&(amp|lt|gt|quot|#\d+|#x[0-9a-f]+|[a-z]+);/i.test(x.title)) x.title = new DOMParser().parseFromString('<p>' + x.title + '</p>', 'text/html').body.textContent;
    if (x.format !== 'pdf') {
      const h = (htmlMap && htmlMap[x.id]) || (x.format === 'html' && d.html) || textToHtml(x.text || ''); x.html = h; x.live = !!(htmlMap && htmlMap[x.id]); if (/^<!doctype/i.test(h)) x.format = 'page'; else if (x.format === 'page') x.format = 'html';
      if (!x.title || /^https?:\/\//.test(x.title)) x.title = x.title || 'Untitled';
      const body = pageBody(h, x.format); const offs = new Map();
      x.text = walkText(body, (n, o) => offs.set(n, o));
      const firstOff = el => { const w = document.createTreeWalker(el, 4); while (w.nextNode()) if (offs.has(w.currentNode) && w.currentNode.data.trim()) return offs.get(w.currentNode); return null; };
      x.links = []; body.querySelectorAll('a[href]').forEach(a => { const hr = a.getAttribute('href') || ''; if (/^#/.test(hr) || a.closest('sup')) return; let abs = null; try { abs = new URL(hr, x.url || (x.wiki ? 'https://en.wikipedia.org/wiki/' : location.href)).href; } catch (e) { return; } if (!/^https?:/.test(abs)) return; const o = firstOff(a); const tx = a.textContent.replace(/\s+/g, ' ').trim(); if (o === null || !tx) return; const i = x.text.indexOf(tx, Math.max(0, o - 2)); if (i < 0 || i > o + 4) return; x.links.push({ s: i, e: i + tx.length, href: abs }); });
      body.querySelectorAll('[data-t]').forEach(el => { const o = firstOff(el); if (o !== null) (x.tmarks = x.tmarks || []).push({ o, t: +el.getAttribute('data-t') }); }); if (x.tmarks) x.tmarks.sort((a, b) => a.o - b.o);
      body.querySelectorAll('h1,h2,h3,h4,h5,h6').forEach(el => { const o = firstOff(el); const tx = el.textContent.replace(/\s+/g, ' ').trim(); if (o !== null && tx) x.heads.push({ lv: +el.tagName[1], text: tx, o, e: o + tx.length }); });
      body.querySelectorAll('p,li,tr,blockquote,dd,figcaption,pre').forEach(el => { const o = firstOff(el); if (o !== null) x.blocks.push(o); });
      x.heads.sort((a, b) => a.o - b.o); x.blocks.sort((a, b) => a - b);
    }
    if (hdF(x.id)) { HD_TR.docs.push({ id: x.id, title: x.title, type: x.type, text: x.text }); hdT('text', 'walk', x.format === 'pdf' ? 'Took ' + x.text.length + ' characters from the PDF text layer' : 'Walked the page tree: ' + x.text.length + ' characters of text, ' + x.heads.length + ' headings, ' + x.blocks.length + ' blocks, ' + (x.links || []).length + ' links', { doc: x.id, chars: x.text.length }); }
    return x; });
  const sts = []; const found = []; const alias = {}; const info = {}; const HY = hdHygiene(docs);
  docs.forEach(d => { const on = hdF(d.id); const ss = splitSentences(d.text, on ? (a, b, c, x) => hdT(a, b, c, { doc: d.id, ...x }) : null); if (on) hdT('sentences', 'split', 'Split into ' + ss.length + ' statements', { doc: d.id, n: ss.length }); const hy = HY ? HY.forDoc(d, on ? (k, what, why) => hdT('names', 'hygiene', why + ' (' + qW(what) + ')', { doc: d.id }) : null) : null; ss.forEach((se, i) => {
    const ns = hdEngineMerge(se.t, findNames(se.t, hy), d.eng, hy);
    ns.forEach(n => { if (n.alias) alias[n.alias] = n.name; });
    const st0 = { id: d.id + ':' + i, doc: d.id, s: se.s, e: se.e, text: se.t, rawNames: ns, figs: findFigures(se.t), dates: findDates(se.t), frame: frameOf(se.t) }; sts.push(st0);
    if (on) { const D = { doc: d.id, id: st0.id }; hdT('sentences', 'statement', 'Statement ' + (i + 1) + ': \u201c' + hdCut(se.t, 90) + '\u201d', { ...D, s: se.s, e: se.e });
      ns.forEach(n => hdT('names', 'name', 'Name \u201c' + n.name + '\u201d' + (n.title ? ' after the title ' + n.title : '') + (n.alias ? ', short form (' + n.alias + ')' : '') + (n.saidAfter ? ', followed by a reporting verb' : '') + (n.acr ? ', an acronym' : '') + (n.engineAdded ? ', found by the engine (' + n.engine + ')' : n.engine ? ', the engine read it too' : ''), { ...D, name: n.name, s: se.s + n.s, e: se.s + n.e }));
      st0.figs.forEach(g => hdT('figures', 'figure', 'Figure \u201c' + g.raw + '\u201d = ' + g.value.toLocaleString() + ' ' + g.label, { ...D, s: se.s + g.s, e: se.s + g.e }));
      st0.dates.forEach(g => hdT('dates', 'date', 'Date \u201c' + g.raw + '\u201d' + (g.year ? ' (year ' + g.year + ')' : ''), { ...D, s: se.s + g.s, e: se.s + g.e }));
      hdT('frame', 'frame', 'Frame: ' + st0.frame + ({ uncertain: ' (a hedge word)', attributed: ' (a reporting verb)', plan: ' (a future or intent word)', fact: ' (no hedge, report or plan word)' })[st0.frame], { ...D, frame: st0.frame }); }
  }); });
  const lastMap = {};
  sts.forEach(st => st.rawNames.forEach(n => { const w = n.name.split(' '); const l = w[w.length - 1]; if (w.length > 1 && !ORG.has(l) && !PLACE.has(l)) (lastMap[l] = lastMap[l] || new Set()).add(n.name); }));
  const allRaw = [...new Set(sts.flatMap(st => st.rawNames.map(n => n.name)))];
  const nest = (short, long) => { const a = short.split(' '), b = long.split(' '); if (b.length <= a.length) return false; return a.every((w, i) => b[i] === w) || a.every((w, i) => b[b.length - a.length + i] === w); };
  const canonMemo = new Map(); const canonOf = nm => { let v = canonMemo.get(nm); if (v === undefined) { v = canonOf0(nm); canonMemo.set(nm, v); } return v; };
  const byFirst = new Map(), byLast = new Map(); allRaw.forEach(o => { if (!o.includes(' ')) return; const w = o.split(' '); const f0 = w[0], l0 = w[w.length - 1]; (byFirst.get(f0) || byFirst.set(f0, []).get(f0)).push(o); (byLast.get(l0) || byLast.set(l0, []).get(l0)).push(o); });
  // a longer name may absorb a shorter one only if the longer one recurs itself (2+ statements, the bar holoName uses):
  // otherwise one stray capitalised run (measured: word salad's “Office The Brookmeade Park”) renames a real place everywhere
  const rawN = new Map(); sts.forEach(st => new Set(st.rawNames.map(n => n.name)).forEach(n => rawN.set(n, (rawN.get(n) || 0) + 1)));
  const canonOf0 = nm => {
    if (alias[nm]) return alias[nm];
    if (nm.includes(' ')) { const w = nm.split(' '); const pool = [...new Set([...(byFirst.get(w[0]) || []), ...(byLast.get(w[w.length - 1]) || [])])]; const c = pool.filter(o => nest(nm, o)).sort((x, y) => y.length - x.length); if (c.length && c.every(o => o === c[0] || nest(o, c[0])) && (rawN.get(c[0]) || 0) >= 2) return c[0]; return nm; }
    return lastMap[nm] && lastMap[nm].size === 1 && (rawN.get([...lastMap[nm]][0]) || 0) >= 2 ? [...lastMap[nm]][0] : nm;
  };
  const names = {}; const aliasOf = {}; Object.keys(alias).forEach(a => { (aliasOf[alias[a]] = aliasOf[alias[a]] || []).push(a); });
  sts.forEach(st => {
    st.spans = []; const set = new Set();
    st.rawNames.forEach(n => {
      const canon = canonOf(n.name);
      if (canon !== n.name && hdF(st.doc)) hdT('canon', 'merge', '\u201c' + n.name + '\u201d is read as \u201c' + canon + '\u201d (' + (alias[n.name] ? 'declared in parentheses' : n.name.includes(' ') ? 'it sits inside that longer name' : 'the only full name ending in it') + ')', { doc: st.doc, id: st.id, from: n.name, to: canon });
      if (n.alias && n.alias === canon) return;
      const I = info[canon] || (info[canon] = { aliases: new Set() });
      if (n.title) I.person = true; if (n.saidAfter) I.said = true; if (n.acr && !alias[n.name]) I.acr = true;
      if (canon !== n.name) I.aliases.add(n.name);
      (aliasOf[canon] || []).forEach(a => I.aliases.add(a));
      st.spans.push({ s: n.s, e: n.e, name: canon }); set.add(canon);
    });
    st.names = [...set];
    st.names.forEach(n => { (names[n] = names[n] || { name: n, sts: [], docs: new Set() }); names[n].sts.push(st.id); names[n].docs.add(st.doc); });
    const d = docs.find(x => x.id === st.doc);
    const y = st.dates.find(x => x.year);
    st.year = d.year || (y ? y.year : null);
    st.ownDate = st.dates.length > 0;
    const words = st.text.replace(/https?:\/\/\S+/g, ' ').toLowerCase().match(/[a-z]{4,}/g) || [];
    const nameWords = new Set(st.names.join(' ').toLowerCase().split(/\s+/));
    st.topics = [...new Set(words.filter(w => !STOP.has(w) && !nameWords.has(w) && !MONTHS.has(w[0].toUpperCase() + w.slice(1))).map(w => w.length > 4 ? w.replace(/(ies)$/, 'y').replace(/([^s])s$/, '$1') : w))];
  });
  Object.values(names).forEach(n => { const I = info[n.name] || {}; n.type = nameType(n.name, I); n.aliases = [...(I.aliases || [])]; });
  if (HD_TR) Object.values(names).forEach(n => { if (![...n.docs].some(hdF)) return; const I = info[n.name] || {}; hdT('canon', 'type', n.name + ' \u2192 ' + n.type + (I.person ? ' (had a title)' : I.said ? ' (followed by a reporting verb)' : I.acr ? ' (an acronym)' : n.type === 'other' ? ' (no rule matched)' : ' (by its first or last word)') + ' \u00b7 ' + n.sts.length + ' mention' + (n.sts.length === 1 ? '' : 's') + ' in ' + n.docs.size + ' source' + (n.docs.size === 1 ? '' : 's'), { name: n.name, type: n.type, mentions: n.sts.length, docsN: n.docs.size }); });
  { const DM = new Map(docs.map(x => [x.id, x])); sts.forEach(st => { st.where = whereOf(DM.get(st.doc), st.s); }); }
  const furn = {}; docs.forEach(d => { const set = new Set(); const nt = t => clean(t).toLowerCase().replace(/[^a-z0-9]/g, ''); if (d.title) set.add(nt(d.title)); (d.heads || []).forEach(h => set.add(nt(h.text))); const H = d.heads || []; const back = []; H.forEach((h, i) => { if (!/^(external links|references|further reading|notes|citations|sources|bibliography|see also|footnotes|works cited|general and cited references)\b/i.test(h.text)) return; let e = Infinity; for (let j = i + 1; j < H.length; j++) if (H[j].lv <= h.lv) { e = H[j].o; break; } back.push([h.o, e]); }); furn[d.id] = { set, nt, back }; });
  const aboutDocs = new Set(docs.filter(d => d.aboutOnly).map(d => d.id));
  sts.forEach(st => { st.ref = isJunk(st, furn[st.doc]) || aboutDocs.has(st.doc); const w = clean(st.text).replace(/https?:\/\/\S+/g, ' ').match(/[A-Za-z]{2,}/g) || []; st.claimy = !st.ref && w.length >= 8 && VERB_RE.test(st.text); if (hdF(st.doc)) hdT('junk', st.ref ? 'ref' : st.claimy ? 'claim' : 'thin', st.ref ? 'Set aside as reference matter: \u201c' + hdCut(st.text, 50) + '\u201d' : st.claimy ? 'Kept as a claim (8+ words and a verb)' : 'Kept, but too thin to count as a claim', { doc: st.doc, id: st.id }); });
  sts.forEach(st => { st.shadow = [st.frame, [...new Set(st.names.map(n => (names[n] || {}).type))].sort().join('+'), [...new Set(st.figs.map(g => g.unit))].sort().join('+'), st.dates.length ? 'dated' : ''].join('|'); });
  // a measured doc's sentences are our own description of an image, sound or score: their wording is a template, so they
  // would echo each other (and anything sharing the template words) by form, not content. They stay out of echo matching.
  const measuredD = new Set(docs.filter(d => d.measured).map(d => d.id));
  // a record (provenance sidecar, manifest, data table, URL list) is fields, not sentences: its rows echo prose only by
  // sharing the workspace's subject words, so it stays out of echo matching. Exact structure tests, no threshold.
  const recordD = new Set(docs.filter(d => { const ext = ((String(d.url || '').split(/[?#]/)[0].match(/\.([a-z0-9]+)$/i) || [])[1] || d.type || '').toLowerCase(); if (/^(json|jsonl|ndjson|csv|tsv|xml|ya?ml)$/.test(ext)) return true; const ls = String(d.text || '').split(/\r?\n/).filter(l => l.trim()); if (ls.length && ls.every(l => /^https?:\/\/\S+$/.test(l.trim()))) return true; try { const j = JSON.parse(d.text); return !!j && typeof j === 'object'; } catch (e) { return false; } }).map(d => d.id));
  if (HD_TR && docs.some(d => hdF(d.id) && recordD.has(d.id))) hdT('echo', 'skip', 'Left ' + docs.filter(d => hdF(d.id) && recordD.has(d.id)).length + ' record file(s) out of echo matching: their rows are fields, not sentences, so any echo would be of shared subject words, not content');
  const byD = {}; sts.forEach((st, i) => { if (!st.ref && st.claimy && !measuredD.has(st.doc) && !recordD.has(st.doc)) (byD[st.doc] = byD[st.doc] || []).push(i); });
  if (HD_TR && docs.some(d => hdF(d.id) && d.measured)) hdT('echo', 'skip', 'Left the measured description out of echo matching: its sentences are our template, so any echo would be of wording, not content');
  const lists = Object.values(byD); const IX = []; for (let r = 0; IX.length < 1600 && lists.some(l => r < l.length); r++) lists.forEach(l => { if (r < l.length && IX.length < 1600) IX.push(l[r]); });
  const N = IX.length;
  // exact sparse vectors, no hashing: a topic word counts by how rare it is among the claims compared, a name twice that (holodeck-echo.js)
  const dfT = new Map(); IX.forEach(i => { sts[i].topics.forEach(w => dfT.set(w, (dfT.get(w) || 0) + 1)); sts[i].names.forEach(n => dfT.set('n:' + n, (dfT.get('n:' + n) || 0) + 1)); });
  const wt = (k, m) => m * Math.log(1 + N / dfT.get(k));
  const EC = N > 1 ? HDEcho.echoPairs(IX.map(i => { const t = new Map(); sts[i].topics.forEach(w => t.set(w, wt(w, 1))); sts[i].names.forEach(n => t.set('n:' + n, wt('n:' + n, 2))); return { doc: sts[i].doc, terms: t }; })) : { pairs: [], floor: 1, maxima: [] };
  const echoFloor = EC.floor;
  if (HD_TR && HD_TR.focus.size) { const mine = sts.filter(st => hdF(st.doc) && st.claimy && !st.ref).length, inIX = IX.filter(i => hdF(sts[i].doc)).length; hdT('echo', 'vectors', 'Weighted each claim\u2019s topic words (rarer words count more) and names (twice) into an exact word vector, with no hashing; ' + inIX + ' of your ' + mine + ' claims are among the ' + N + ' compared', { n: N, mine, inIX }); hdT('echo', 'null', 'Null: the same words shuffled across the claims ' + EC.maxima.length + ' times; the largest cosine each claim reached to another source in any draw is its own floor (lowest ' + EC.floor.toFixed(3) + ', shortest claims highest)', { floor: EC.floor, nullN: EC.maxima.length, hist: EC.maxima }); }
  const echoes = {};
  EC.pairs.forEach(({ a, b, sim, ab, ba }) => { const i = IX[a], j = IX[b]; if (sts[i].text === sts[j].text) return; if (ab) (echoes[sts[i].id] = echoes[sts[i].id] || []).push({ id: sts[j].id, sim }); if (ba) (echoes[sts[j].id] = echoes[sts[j].id] || []).push({ id: sts[i].id, sim }); });
  Object.values(echoes).forEach(l => { l.sort((a, b) => b.sim - a.sim); l.length = Math.min(l.length, 4); });
  if (HD_TR && HD_TR.focus.size) { const byIdE = new Map(sts.map(x => [x.id, x])); const dt = id => (docs.find(x => x.id === id) || {}).title || id; sts.forEach(st => { if (!hdF(st.doc)) return; (echoes[st.id] || []).forEach(e => { const o = byIdE.get(e.id); hdT('echo', 'pair', 'Echo ' + e.sim.toFixed(2) + ' with \u201c' + hdCut(o.text, 50) + '\u201d in ' + hdCut(dt(o.doc), 40), { doc: st.doc, id: st.id, other: e.id, otherDoc: o.doc, otherTitle: dt(o.doc), sim: e.sim, mine: hdF(o.doc) }); }); }); }
  const stsByDoc = {}; sts.forEach(s => { (stsByDoc[s.doc] = stsByDoc[s.doc] || []).push(s); });
  return { stsByDoc, echoes, echoFloor, docs, sts, names, byId: Object.fromEntries(sts.map(s => [s.id, s])), docById: Object.fromEntries(docs.map(d => [d.id, d])) };
}
const CITE_RE = /\[(?:\d+|[a-z]|[ivx]+|citation needed|note \d+|nb \d+|update)\]/gi;
const clean = t => (t || '').replace(CITE_RE, '').replace(/\s+([.,;:])/g, '$1').replace(/\s{2,}/g, ' ').trim();
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const BLOCK_RE = /^(P|DIV|H[1-6]|LI|TR|TABLE|UL|OL|DL|DT|DD|BLOCKQUOTE|PRE|SECTION|ARTICLE|HEADER|FOOTER|FIGURE|FIGCAPTION|CAPTION|HR|MAIN|ASIDE|TBODY|THEAD)$/;
function walkText(root, fn) {
  let out = '';
  const rec = n => { for (const c of [...n.childNodes]) {
    if (c.nodeType === 3) { if (fn) fn(c, out.length); out += c.data; }
    else if (c.nodeType === 1) { const tg = c.tagName;
      if (tg === 'BR') { out += '\n'; continue; }
      if (/^(NAV|BUTTON|SELECT|OPTION|FORM|FOOTER|MENU|DIALOG)$/.test(tg) || (tg === 'A' && /^#/.test(c.getAttribute('href') || '')) || (c.getAttribute && (c.getAttribute('aria-hidden') === 'true' || /^(navigation|menu|menubar|banner|contentinfo|dialog)$/.test(c.getAttribute('role') || '')))) continue;
      if (tg === 'IMG' || tg === 'SCRIPT' || tg === 'STYLE' || tg === 'NOSCRIPT' || tg === 'TEMPLATE' || tg === 'SVG' || tg === 'svg' || tg === 'HEAD' || tg === 'TITLE') continue;
      rec(c);
      if (tg === 'TD' || tg === 'TH') out += '; ';
      else if (BLOCK_RE.test(tg) && !out.endsWith('\n')) out += '\n';
    } } };
  rec(root); return out;
}
function whereOf(d, off) {
  if (!d) return '';
  if (d.tmarks && d.tmarks.length) { let t = null; for (const m of d.tmarks) { if (m.o > off) break; t = m.t; } return t === null ? 'Opening' : 'At ' + fmtT(t); }
  if (d.format === 'pdf' && d.pages && d.pages.length) { let p = 0; while (p + 1 < d.pages.length && d.pages[p + 1] <= off) p++; return 'Page ' + (p + 1); }
  const stack = []; let isHead = false;
  for (const h of d.heads || []) { if (h.o > off) break; while (stack.length && stack[stack.length - 1].lv >= h.lv) stack.pop(); stack.push(h); if (off >= h.o && off < h.e + 1) isHead = true; }
  const secStart = stack.length ? stack[stack.length - 1].o : 0;
  const n = (d.blocks || []).filter(b => b >= secStart && b <= off).length;
  const path = stack.map(h => h.text.length > 40 ? h.text.slice(0, 39) + '…' : h.text);
  if (isHead) return (path.length ? path.join(' › ') : 'Top') + ' · heading';
  return path.length ? path.join(' › ') : 'Opening';
}
function pageBody(h, format) { return format === 'page' ? new DOMParser().parseFromString(h || '', 'text/html').body : new DOMParser().parseFromString('<body>' + (h || '') + '</body>', 'text/html').body; }
const TAG_STYLE = {
  H1: "font:500 30px/1.25 'Newsreader',serif;margin:26px 0 12px", H2: "font:500 25px/1.3 'Newsreader',serif;margin:30px 0 10px;padding-bottom:6px;border-bottom:1px solid var(--line)",
  H3: "font:600 18px/1.35 'Hanken Grotesk',sans-serif;margin:22px 0 8px", H4: "font:600 16px/1.4 'Hanken Grotesk',sans-serif;margin:18px 0 6px", H5: "font:600 15px 'Hanken Grotesk',sans-serif;margin:16px 0 6px", H6: "font:600 14px 'Hanken Grotesk',sans-serif;margin:14px 0 6px",
  P: 'margin:0 0 14px', UL: 'margin:0 0 14px;padding-left:24px', OL: 'margin:0 0 14px;padding-left:24px', LI: 'margin:4px 0',
  BLOCKQUOTE: 'margin:0 0 14px;padding:4px 16px;border-left:3px solid var(--line2);color:var(--ink2)',
  TABLE: "border-collapse:collapse;margin:0 0 18px;font:400 14px/1.45 'Hanken Grotesk',sans-serif;max-width:100%", TD: 'border:1px solid var(--line);padding:6px 8px;vertical-align:top', TH: 'border:1px solid var(--line);padding:6px 8px;text-align:left;vertical-align:top;background:var(--s2);font-weight:600',
  CAPTION: 'font-weight:600;padding:6px 0;text-align:left', IMG: 'max-width:100%;height:auto;border-radius:6px', FIGURE: 'margin:0 0 16px', FIGCAPTION: "font:400 13px/1.45 'Hanken Grotesk',sans-serif;color:var(--mut);margin-top:6px",
  A: 'color:inherit;text-decoration:underline;text-decoration-color:var(--line2);text-decoration-thickness:1px;text-underline-offset:3px', PRE: "font:400 13px/1.5 'JetBrains Mono',monospace;background:var(--s2);padding:12px;border-radius:8px;white-space:pre-wrap;margin:0 0 14px", CODE: "font:400 .9em 'JetBrains Mono',monospace",
  HR: 'border:0;border-top:1px solid var(--line);margin:22px 0', DT: 'font-weight:600', DD: 'margin:0 0 8px 16px'
};
function textToHtml(t) { t = (t || '').replace(/\r\n?/g, '\n'); const blocks = /\n\s*\n/.test(t) ? t.split(/\n\s*\n+/) : t.split('\n'); return blocks.map(b => b.trim()).filter(Boolean).map(b => '<p style="' + TAG_STYLE.P + '">' + esc(b).replace(/\n/g, '<br>') + '</p>').join(''); }

export function analyze_offline(corpus, htmlMap) { return analyze(corpus, htmlMap); }
